# for test only no sensitive data here
kind: Secret
apiVersion: v1
metadata:
  name: timetime-secret
data:
  API_KEY: bXktc3VwZXItc2VjcmV0LWFwaS1rZXk=
  DB_PASSWORD: czNjdXIzUEBzc3cwcmQ=
type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: timetime-config
data:
  APP_ENV: production
  APP_NAME: timetime
  DEFAULT_TIMEZONE: Asia/Bangkok
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: timetime
  namespace: userx
  labels:
    app: timetime
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: timetime
  template:
    metadata:
      labels:
        deployment: timetime
    spec:
      containers:
        - name: timetime
          image: 'quay.io/rh_ee_swongpai/timetime:userx'
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: timetime-config
            - secretRef:
                name: timetime-secret
      restartPolicy: Always