# replace <SELECT_NODE_NAME> with the node name you want to schedule the pod on
kind: Deployment
apiVersion: apps/v1
metadata:
  name: timetime
  namespace: userx
  labels:
    app: timetime
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: timetime
  template:
    metadata:
      labels:
        deployment: timetime
    spec:
      nodeSelector:
        kubernetes.io/hostname: <SELECT_NODE_NAME>
      containers:
        - name: timetime
          image: 'quay.io/rh_ee_swongpai/timetime:userx'
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: timetime-config
            - secretRef:
                name: timetime-secret
      restartPolicy: Always